# Generated by Django 5.1.4 on 2025-01-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('qno', models.IntegerField(primary_key=True, serialize=False)),
                ('qtext', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=50)),
                ('op1', models.CharField(max_length=50)),
                ('op2', models.CharField(max_length=50)),
                ('op3', models.CharField(max_length=50)),
                ('op4', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=20)),
                ('score', models.IntegerField()),
            ],
            options={
                'db_table': 'result',
            },
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('mobno', models.IntegerField()),
            ],
            options={
                'db_table': 'userdata',
            },
        ),
    ]
